<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address11 CDATA #IMPLIED>
  <!ATTLIST ROW Address21 CDATA #IMPLIED>
  <!ATTLIST ROW Address31 CDATA #IMPLIED>
  <!ATTLIST ROW Address41 CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber1 CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy1 CDATA #IMPLIED>
  <!ATTLIST ROW Author1 CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy1 CDATA #IMPLIED>
  <!ATTLIST ROW Comment1 CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName1 CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind1 CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind1 CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description1 CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL1 CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description1 CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL1 CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate1 CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime1 CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion1 CDATA #IMPLIED>
  <!ATTLIST ROW Date1 CDATA #IMPLIED>
  <!ATTLIST ROW Description1 CDATA #IMPLIED>
  <!ATTLIST ROW Designator1 CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_1 CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_1 CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_1 CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_1 CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId1 CDATA #IMPLIED>
  <!ATTLIST ROW Document1 CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName1 CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName1 CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber1 CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy1 CDATA #IMPLIED>
  <!ATTLIST ROW Engineer1 CDATA #IMPLIED>
  <!ATTLIST ROW Footprint1 CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_1 CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_1 CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model1 CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath1 CDATA #IMPLIED>
  <!ATTLIST ROW Index1 CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID1 CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate1 CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote1 CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name1 CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference1 CDATA #IMPLIED>
  <!ATTLIST ROW LibRef1 CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator1 CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint1 CDATA #IMPLIED>
  <!ATTLIST ROW Model_PCB3D1 CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity1 CDATA #IMPLIED>
  <!ATTLIST ROW Models1 CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate1 CDATA #IMPLIED>
  <!ATTLIST ROW Organization1 CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription1 CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference1 CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion1 CDATA #IMPLIED>
  <!ATTLIST ROW PartType1 CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D1 CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath1 CDATA #IMPLIED>
  <!ATTLIST ROW Pins1 CDATA #IMPLIED>
  <!ATTLIST ROW Project1 CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName1 CDATA #IMPLIED>
  <!ATTLIST ROW Published1 CDATA #IMPLIED>
  <!ATTLIST ROW Publisher1 CDATA #IMPLIED>
  <!ATTLIST ROW Quantity1 CDATA #IMPLIED>
  <!ATTLIST ROW Revision1 CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID1 CDATA #IMPLIED>
  <!ATTLIST ROW Rule1 CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber1 CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal1 CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity1 CDATA #IMPLIED>
  <!ATTLIST ROW Simulation1 CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName1 CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts1 CDATA #IMPLIED>
  <!ATTLIST ROW Time1 CDATA #IMPLIED>
  <!ATTLIST ROW Title1 CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName1 CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath1 CDATA #IMPLIED>
  <!ATTLIST ROW Variant1 CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID1 CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address11" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address21" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address31" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address41" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber1" Caption="Application_BuildNumber" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy1" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author1" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy1" Caption="CheckedBy" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Comment1" Caption="Comment" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="CompanyName1" Caption="CompanyName" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind1" Caption="Component Kind" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind1" Caption="ComponentKind" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description1" Caption="ComponentLink1Description" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL1" Caption="ComponentLink1URL" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description1" Caption="ComponentLink2Description" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL1" Caption="ComponentLink2URL" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate1" Caption="CurrentDate" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime1" Caption="CurrentTime" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion1" Caption="DatasheetVersion" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Date1" Caption="Date" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="Description1" Caption="Description" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="Designator1" Caption="Designator" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_1" Caption="Designator-X&#40;Mil&#41;" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_1" Caption="Designator-X&#40;mm&#41;" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_1" Caption="Designator-Y&#40;Mil&#41;" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_1" Caption="Designator-Y&#40;mm&#41;" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId1" Caption="DesignItemId" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Document1" Caption="Document" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName1" Caption="DocumentFullPathAndName" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="DocumentName1" Caption="DocumentName" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber1" Caption="DocumentNumber" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy1" Caption="DrawnBy" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Engineer1" Caption="Engineer" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Footprint1" Caption="Footprint" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_1" Caption="Height&#40;Mil&#41;" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_1" Caption="Height&#40;mm&#41;" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model1" Caption="Ibis Model" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="ImagePath1" Caption="ImagePath" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Index1" Caption="Index" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID1" Caption="ItemGUID" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate1" Caption="LatestRevisionDate" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote1" Caption="LatestRevisionNote" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Library_Name1" Caption="Library Name" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference1" Caption="Library Reference" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="LibRef1" Caption="LibRef" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator1" Caption="LogicalDesignator" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint1" Caption="Model:Footprint" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Model_PCB3D1" Caption="Model:PCB3D" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity1" Caption="Model:Signal Integrity" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="Models1" Caption="Models" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate1" Caption="ModifiedDate" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Organization1" Caption="Organization" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription1" Caption="PackageDescription" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="PackageReference1" Caption="PackageReference" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion1" Caption="PackageVersion" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="PartType1" Caption="PartType" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="PCB3D1" Caption="PCB3D" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath1" Caption="PhysicalPath" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Pins1" Caption="Pins" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Project1" Caption="Project" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="ProjectName1" Caption="ProjectName" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Published1" Caption="Published" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Publisher1" Caption="Publisher" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="Quantity1" Caption="Quantity" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Revision1" Caption="Revision" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID1" Caption="RevisionGUID" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="Rule1" Caption="Rule" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber1" Caption="SheetNumber" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal1" Caption="SheetTotal" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity1" Caption="Signal Integrity" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="Simulation1" Caption="Simulation" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName1" Caption="SourceLibraryName" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts1" Caption="Sub-Parts" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Time1" Caption="Time" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Title1" Caption="Title" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName1" Caption="UniqueIdName" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath1" Caption="UniqueIdPath" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Variant1" Caption="Variant" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID1" Caption="VaultGUID" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_1_1" Designator_X_Mil_1="6000" Designator_X_mm_1="152.4" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="1" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_1_1" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="CSLXXXWS" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_1_2" Designator_X_Mil_1="8300" Designator_X_mm_1="210.82" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="2" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_1_2" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="FHWGRUWN" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_2_1" Designator_X_Mil_1="10400" Designator_X_mm_1="264.16" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="3" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_2_1" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="CQURVRUK" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_2_2" Designator_X_Mil_1="12700" Designator_X_mm_1="322.58" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="4" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_2_2" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="IGUPYRLV" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_3_1" Designator_X_Mil_1="14900" Designator_X_mm_1="378.46" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="5" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_3_1" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="KNJGOHYX" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="CD54HCT238" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="Manufacturer Link" ComponentLink1URL1="http://www.ti.com/" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="Jun-1989" Date1="" Description1="3-Line to 8-Line Decoder / Demultiplexer" Designator1="DEMUX_3_2" Designator_X_Mil_1="17200" Designator_X_mm_1="436.88" Designator_Y_Mil_1="7500" Designator_Y_mm_1="190.5" DesignItemId1="SN54HC238J" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="J016D" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="6" ItemGUID1="" LatestRevisionDate1="04-Mar-2005" LatestRevisionNote1="Stylized 3D Model Added." Library_Name1="TI Logic Decoder Demux.IntLib" Library_Reference1="SN54HC238J" LibRef1="SN54HC238J" LogicalDesignator1="DEMUX_3_2" Model_Footprint1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_PCB3D1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" Model_Signal_Integrity1="" Models1="3" ModifiedDate1="" Organization1="" PackageDescription1="DIP; 16 Leads; Row Spacing 7.62 mm; Pitch 2.54 mm" PackageReference1="J016D" PackageVersion1="Jun-1999" PartType1="CD54HCT238" PCB3D1="J016" PhysicalPath1="DC_Switch_2" Pins1="16" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="8-Jun-2000" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="SN54HC238J" Simulation1="" SourceLibraryName1="TI Logic Decoder Demux.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="GTDSVEYI" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>
    <ROW Address11="" Address21="" Address31="" Address41="" Application_BuildNumber1="" ApprovedBy1="" Author1="" CheckedBy1="" Comment1="Arduino Pins" CompanyName1="" Component_Kind1="Standard" ComponentKind1="0" ComponentLink1Description1="" ComponentLink1URL1="" ComponentLink2Description1="" ComponentLink2URL1="" CurrentDate1="" CurrentTime1="" DatasheetVersion1="" Date1="" Description1="Header, 15-Pin, Dual row" Designator1="Main Connector" Designator_X_Mil_1="10900" Designator_X_mm_1="276.86" Designator_Y_Mil_1="3600" Designator_Y_mm_1="91.44" DesignItemId1="Header 15X2A" Document1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_2.SchDoc" DocumentFullPathAndName1="" DocumentName1="" DocumentNumber1="" DrawnBy1="" Engineer1="" Footprint1="HDR2X15_CEN" Height_Mil_1="0" Height_mm_1="0" Ibis_Model1="" ImagePath1="" Index1="7" ItemGUID1="" LatestRevisionDate1="17-Jul-2002" LatestRevisionNote1="Re-released for DXP Platform." Library_Name1="Miscellaneous Connectors.IntLib" Library_Reference1="Header 15X2A" LibRef1="Header 15X2A" LogicalDesignator1="Main Connector" Model_Footprint1="Connector; Header; 15x2 Position" Model_PCB3D1="" Model_Signal_Integrity1="" Models1="2" ModifiedDate1="" Organization1="" PackageDescription1="" PackageReference1="" PackageVersion1="" PartType1="Arduino Pins" PCB3D1="" PhysicalPath1="DC_Switch_2" Pins1="30" Project1="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;DC_Switch_Project_2&#92;DC_Switch_Project_2.PrjPcb" ProjectName1="" Published1="" Publisher1="Altium Limited" Quantity1="1" Revision1="" RevisionGUID1="" Rule1="" SheetNumber1="" SheetTotal1="1" Signal_Integrity1="Connector" Simulation1="" SourceLibraryName1="Miscellaneous Connectors.IntLib" Sub_Parts1="1" Time1="" Title1="" UniqueIdName1="YYGWJCWF" UniqueIdPath1="" Variant1="" VaultGUID1=""></ROW>